### ISSUE TITLE
Timeline pins/notifications - Rebble

### ISSUE THREAD

**Issue by tumbleweed05** [Wowfunhappy/Pebble-RSS-Reader#19]
Would it be difficult to fix timeline pins/notifs for Rebble subscribers?

**Comment by Wowfunhappy** [comment]
Hi, there's nothing to "fix", this has never been a feature of the app.

What is the use case you were thinking of? It would only really make sense on "timeline past", which is semi-hidden in the latest firmware.

**Comment by tumbleweed05** [comment]
How interesting! Not many apps show the timeline options and thought this would be a quick fix. This issue can be closed.

![image](https://user-images.githubusercontent.com/6808861/197407278-1bd78bd0-2a0e-4c59-a34e-d6355ba8d08d.jpeg)
