### ISSUE TITLE
White screen on OG Steel

### ISSUE THREAD

**Issue by Cralex** [Wowfunhappy/Pebble-RSS-Reader#3]
Tried installing it on my OG steel connected to my iPhone. It replaced SimplyJS and tried to load on my watch, but it only displayed a white screen on my watch after it finished transferring. I tried deleting it and reinstalling it and the same thing happens. Trying to open the app settings will cause the app to try loading, but it still gets stuck on the white screen and the settings page on the phone never loads.

This seems similar to the behavior of an in-development google assistant app that was uploaded to the Rebble Discord. I remember someone saying something about the iPhone’s JS engine working differently? I can try testing other watches or on an android phone to rule out problems.

In the meantime, let me know if there’s anything you want me to try.

**Comment by Wowfunhappy** [comment]
Very odd, and disappointing! I'm on iOS myself, so it's not that!

As I mentioned in the release, I've only tested on a Pebble 2. I expected the app to be a bit screwy on classic models, but I didn't imagine it wouldn't even _load_.

If you have access to a Pebble Time or Pebble 2, I would very much like to know what happens there...

**Comment by castillaa** [comment]
Same behavior on Pebble Time,  using Android.

**Comment by Wowfunhappy** [comment]
Pretty sure I found the problem, Cralex is testing for me.

The app crashes if Settings is empty. And because the app crashes, you can't open Settings. This didn't happen on my phone since I'd populated Settings during development.

ProTip: Since there's no way to clear an app's Settings, I had to temporarily change app's UUID in order to replicate this.

**Comment by Wowfunhappy** [comment]
This should be fixed by version 1.1. If not, let me know.
